[project]
name = "djangocourse"
version = "0.1.0"
description = "Django course project"
authors = [
    {name = "Tiamiyu Abdul-salam", email = "128032488+kolacodehub@users.noreply.github.com"}
]
requires-python = ">=3.13"
dependencies = [
    "django>=5.0.1",
    "django-allauth[socialaccount] (>=65.11.2,<66.0.0)",
    "psycopg (>=3.2.10,<4.0.0)",
    "dj-database-url (>=3.0.1,<4.0.0)",
    "django-widget-tweaks (>=1.5.0,<2.0.0)",
    "gunicorn (>=23.0.0,<24.0.0)",
    "whitenoise[brotil] (>=6.11.0,<7.0.0)",
    "psycopg2 (>=2.9.10,<3.0.0)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false  # ðŸ‘ˆ tells Poetry: â€œthis is an app, not a publishable packageâ€

[tool.poetry.group.dev.dependencies]
django-debug-toolbar = "^6.0.0"

